### ISSUE TITLE
Display minimap window epic minimap (1)

### ISSUE THREAD

**Issue by RenzoRichter** [claassenlab/cellpose#10]
**As a** user **I want to** have a separate window open when I open a picture in cellpose that shows the whole picture **so that** I can see the whole picture at all times.

**Acceptance criteria:**

- [x] #17
- [x]  The window is smaller than the main window
- [x]  The window shows the whole picture that is open in cellpose  (e.g. like a minimap)
- [x]  The dimensions of the minimap window are proportional to those of the loaded picture, ensuring that e.g. wide pictures result in a wide minimap (keep the aspect ratio).
- [x] ~~The user can adjust the size of the minimap window~~
- [x] ~~The content of the minimap window also adjusts in size as the window is adjusted~~
- [x] The window is initialized with appropriate dimensions

**Optional:**
- [ ] When Cellpose is launched with multiple screens connected, the minimap window should open on a screen other than the one where the main Cellpose window is located.

Note: At this point the area which is viewed in the main window does not need to be reflected in the minimap window. This is just the first step which opens an extra window that shows the same image that was loaded into cellpose.
~~Also: As discussed in team meetings, the size adjustment should not require any extra work. It is still a requirement which is why it is part of this ticket.~~ (It requires too much extra work, we skip it for now).
