### ISSUE TITLE
Navigation on the minimap epic minimap (3)

### ISSUE THREAD

**Issue by RenzoRichter** [claassenlab/cellpose#13]
**As a** Cellpose user **I want to** navigate the main picture in cellpose by click on the minimap **so that**  I can quickly jump to different areas of the image.

**Acceptance criteria:**

- [ ] When clicking on a point on the minimap the main picture in Cellpose displays that area
- [ ] The point of the click becomes the new centre 
- [ ] The part of the picture that is shown is the same size as the part that was shown before the click (same level of zoom)
- [ ] drag-and-drop: When clicking somewhere on the minimap and holding the click and dragging the mouse, the cellpose picture moves along with the mouse as the current centre (as long as the click is held). 

Note: The drag-and-drop requirement is like simulating many clicks as the user holds a click and drags. There is no rate given as to how often this click must be simulated per second, but it should be somewhat smooth (not too little rate) and it should not lead to a crash of cellpose (not too high rate).

**Comment by jakobjo** [comment]
This issue is split into 3 parts:
#44 
#45 
#46 

The "drag" feature is no longer a requirement and will be in a later issue since its not necessary for the working minimap. 

Therefore i close this issue.
