### ISSUE TITLE
New menu for colour options

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#18]
**As a** Cellpose user, **I want** to have a seperate menu on the right hand side of the picture **so that** I will have more space for the colour saturation sliders later.

### Acceptance Criteria

- [x] There is a new menu on the right hand side of the picture in the Cellpose GUI
- [x] The new menu has the same width as the menu on the left hand side (does not have to be hard coded)
- [x] The new menu has the same height as the menu on the left hand side (full length)
- [x] The new menu is scrollable (as the menu on the left hand side)

### Additional Resources:

<img width="673" alt="Bildschirmfoto 2024-05-30 um 09 34 33" src="https://github.com/claassenlab/cellpose/assets/166049959/8c3c1ff2-daa7-4f2c-9a8b-116fc1cba1d6">
 The area highlighted in grey on the right hand side of this picture is the location where the new menu will be added.

### Notes
This is story is for the 2D GUI.

**Comment by JoshuaSchlucke** [comment]
Effort: 8
