### ISSUE TITLE
Move the colour sliders to the right hand side

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#19]
**As a** Cellpose user, **I want** to have the colour-saturation sliders move from the "views"-menu to the new menu on the right, **so that** I will have space for more sliders later.

### Acceptance Criteria

- [x] The 3 colour-saturation sliders are removed from the views menu one the left.
- [x] The 3 colour-saturation sliders are in the new menu on the right hand side.
- [x] There is no empty space in the "views" menu on the location where the sliders were (the "views" menu is smaller, as it now needs less space).

### Additional Resources:

<img width="611" alt="Bildschirmfoto 2024-05-30 um 09 55 57" src="https://github.com/claassenlab/cellpose/assets/166049959/857fa4f7-c630-45bb-9547-4dcd36010b5e">

### Note:

The old "red", "green", "blue", "gray/red" labels next to the sliders can also be removed instead of moving them to the right. Important is that the sliders move to the new location and keep their functionality.

This story is for the 2D GUI.

**Comment by JoshuaSchlucke** [comment]
Effort: 13
