### ISSUE TITLE
Colour-assuming buttons next to sliders

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#20]
**As a** Cellpose user, **I want** to have coloured buttons next to the colour sliders that can assume the colour I choose, **so that** I can assign a colour to each slider manually.

### Acceptance Criteria

For example:
1. If I click on the colour button
2. a colour dialog opens
3. I can choose a colour
4. The button assumes the colour that I chose

- [x] Next to each slider on the right there is a small coloured button (round or rectangle-shaped)
- [x] A colour dialog opens when one clicks on the button
- [x] If one chooses a colour, the button assumes that colour
- [x] The old "red", "green", "blue", "gray/red" labels are removed

### Additional Resources:

<img width="223" alt="Bildschirmfoto 2024-05-30 um 10 15 16" src="https://github.com/claassenlab/cellpose/assets/166049959/2b7f8529-453a-4854-8094-cdbc3c1409fb">

### Notes:
This implementation should be extendable/reusable, meaning that each button should not be hardcoded. More of these buttons will be used later.
The old "red", "green", "blue", "gray/red" labels may have already been removed prior to this. 

This story is for the 2D GUI.

**Comment by JoshuaSchlucke** [comment]
Effort: 5
