### ISSUE TITLE
On-off-Button next to each colour button of the sliders

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#24]
**As a** Cellpose user, **I want** to have a on-off-button next to each colour button of the sliders, **so that** I can turn the button on and off (this will later turn the channel on and off).

### Acceptance Criteria

For example if:
1. I click one of the on-and-off buttons
2. it changes its appearance (so that one can see if it is on or off).

- [x] There are on-off-buttons to the right of the colour buttons of each colour slider.
- [x] The buttons are initialized in the same for-loop as the sliders and the colour buttons for extensibility.
- [x] The button changes its appearance when one clicks it, it has an off-state and an on-state (so that the user can see whether it is on or off).
- [x] The icons used for on and off are publicly availabe and not under any copyright protection.

### Additional Resources:

<img width="315" alt="Bildschirmfoto 2024-06-05 um 16 56 02" src="https://github.com/claassenlab/cellpose/assets/166049959/b63313ba-1ee8-4cd9-a34b-263cd2743bb8">

Note: In this case Red = ON, Purple = OFF, Yellow = OFF. This is just an illustration of the idea.

### Notes:

The for loop that initializes the sliders can be found in the make_buttons method in the MainW class of the gui. This is the location where each button should be initialized/the method should be called that initializes each button.
