### ISSUE TITLE
launch buttons and color dialog with initial colors

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#25]
**As a** User, **I want** the color buttons to assume a default color (red, green and blue) and the color picker to start with the previously selected color  , **so that** it matches the default channels and a new selected color will not get lost on the color picking process.

**effort estimate:**
Team 1: 
Team 2: 5

### Acceptance Criteria

- [ ] color buttons are not black after launching cellpose;
- [ ] they display the default color;
- [ ] the color dialog opens with the previously selected color (currently opens with white, should open with button color).

### Additional Resources:
View menu after launch:
<img src="https://github.com/claassenlab/cellpose/assets/148364763/1fbd8d12-c24d-439d-8aba-41f50b724777" alt="Beispielbild" width="300"/>

### Notes

Hint: for the second part of this feature look at the color picker issue/PR
