### ISSUE TITLE
change color channels using the color buttons

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#26]
Replaced by #53 

**As a** User, **I want** to use the color buttons to change the color of their corresponding channel, **so that** I can assign custom colors to markers.

**effort estimate:**
Team 1:
Team 2: 13

### Acceptance Criteria

Please make sure the following criteria are satisfied
- [ ] The button still displays the chosen color;
- [ ] The channel corresponding to the button is colorized with the selected color;
- [ ] The displayed image is updated with the new color channel;
- [ ] The default colors remain red, green and blue;
- [ ] The saturation sliders still work on their channel.

#### This is how the process of adjusting the channel color should look like:

1. default window after loading any image (red channel selected):
![red_color](https://github.com/claassenlab/cellpose/assets/148364763/1f3f365d-a3ef-4415-8138-7ce84b87a2e8)
2. pick a new color for the red channel (in this case pink).
3. new view after adjusting the color of the first channel:
![new_pink_color](https://github.com/claassenlab/cellpose/assets/148364763/36a95b78-d3e1-4b27-814c-f1586f5fa8d2)

### Notes
The channel selection drop down menu will be changed in the upcoming process, but its not the focus of this ticket, it's okay that it still displays the hardcoded options.
This should be an expandable feature, since we plan to have > 3 channels later on (dont hardcode every channel!).
This feature is important for the users, since later on some markers may have the same colors per default and need to be changed.

If you stumble upon any questions, feel free to contact us.
