### ISSUE TITLE
new export option .csv

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#30]
**As a** Cellpose user, **I want** to have a new .csv export option in the File-menu, **so that** I can export information later.

**effort estimate:**
Team 1: 3
Team 2: 8

### Acceptance Criteria

- [x] There is a new option in the drop-down menu "File" 
- [x] The title of the new option is "Save Features as .csv"
- [x] When the user clicks on "Save Features as .csv" a .csv file is saved
- [x] The file is saved to the same directory that the other export options save to
- [x] The content of the exported .csv does not matter at this point 
- [x] The name of the .csv is as follows: parent.filename_cp_features.csv , where parent.filename is the name of the currently loaded image file.

For example when I:
1. Click the new "Save Features as .csv" button with a file by the name "example_image.tif" loaded
2. a .csv file is saved that is named example_image_cp_features.csv

Optional:
- [x] A available shortcut is added to the new option

### Additional Resources:

<img width="387" alt="Bildschirmfoto 2024-06-11 um 10 42 51" src="https://github.com/claassenlab/cellpose/assets/166049959/a3a2fbf3-2e41-4709-b0fc-c040ae7312f6">

This is where the new button should be added (below or between other options is up to you).
