### ISSUE TITLE
compute features

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#32]
**As a** Cellpose user, **I want** to export features, **so that** I can analyse the segmentation results.

**effort estimate:**
Team 1: 13
Team 2: 13

### Acceptance Criteria

For example:
1. I click on "Save Features as .csv"
2. the features are exported as a .csv

- [x] The feature-matrix of the segmentation is calculated correctly
- [x] The feature matrix accesible, so one can add other export options than .csv later
- [x] The features are calculated for as many channels as there are currently loaded (right now max. 3, later there will be more)
- [x] The rows are labelled "cell 1", "cell 2"... for as many cells as were found
- [x] The columns are labelled "marker 1", "marker 2"... for as many channels as are there.
- [x] The inner cells represent the features
- [x] The features are exported in the desired format (.csv)

### Additional Resources:
Feature formula:
<img width="871" alt="Bildschirmfoto 2024-06-11 um 14 21 30" src="https://github.com/claassenlab/cellpose/assets/166049959/9e43b0ee-621b-4cbc-aa79-c98b1e8e59e6">

### Notes

Information on how to access the masks and cells will be provided through solving #31 .
Contact me if you have any questions about the formula.
