### ISSUE TITLE
turn channels on and off

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#33]
Replaced by #52 

**As a** Cellpose user , **I want** to be able to turn channels on and off visually, **so that** I can view the channels as needed.

**effort estimate:**
Team 1:
Team 2: 13

### Acceptance Criteria

For example:
1. I click on eye-icon next to the blue channel and it is in off-state/on-state
2. the channel visually appears/disappers 

- [ ] When launching cellpose the initial state off the buttons is ON (eye not crossed out) and all (3) channels are visible.
- [ ] When one of the channels is turned off it visually disappears
- [ ] When one of the channels is turned on it visually appears
- [ ] When one channel is turned on/off it does not alter the state of other channels (saturation, on-off state)
- [ ] When one channel is turned on the current saturation controlled by the sliders is applied
- [ ] The implementation is extendable for more channels later

If: #26 has been implemented at this point:
- [ ] The implementation does not interfere with the ability to change channel colours

If:  #26 has not been implemented at this point:
- [ ] The implementation leaves the possibility of adding a feature to change channel colour later

### Additional Resources:
All channels ON and all channels visible:

<img width="876" alt="Bildschirmfoto 2024-06-11 um 16 17 54" src="https://github.com/claassenlab/cellpose/assets/166049959/069175ce-a94a-4a93-8e5e-45cc3de4dfed">

Only the green channel is ON and visible:

<img width="876" alt="Bildschirmfoto 2024-06-11 um 16 18 39" src="https://github.com/claassenlab/cellpose/assets/166049959/5511c79e-bd8f-4917-950a-f984b3c026ba">

### Notes

The dropdown menu on the left side in the "views" section offers similar functionality. The implementation there can be used for inspiration. But the current implementation offers the option to view all three channels or only one, not any combination that is desired by the user (e.g. blue and red together). 
<img width="272" alt="Bildschirmfoto 2024-06-11 um 16 19 17" src="https://github.com/claassenlab/cellpose/assets/166049959/ab4578e6-72f3-4bfc-b94e-ab1440d249dd">
