### ISSUE TITLE
new settings export option in "File" menu

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#34]
**As a** Cellpose user, **I want** have a new option in the "File" menu, **so that** I can export my settings through it later.

**effort estimate:**
Team 1: 8
Team 2: 8

### Acceptance Criteria

For example when I:

1. Click the new "Save Settings as json" button with a file by the name "example_image.tif" loaded
2. a .json file is saved that is named example_image_cp_settings.json

- [x] There is a new option in the drop-down menu "File" 
- [x] The title of the new option is "Save Settings as json"
- [x] When the user clicks on "Save Settings as json" a .json file is saved
- [x] The file is saved to the same directory that the other export options save to
- [x] The content of the exported .json does not matter at this point 
- [x] The name of the json is as follows: parent.filename_cp_settings.json , where parent.filename is the name of the currently loaded image file.

### Additional Resources:
The "File" menu: Add the new option there (in between or below is both fine).

<img width="381" alt="Bildschirmfoto 2024-06-11 um 16 50 54" src="https://github.com/claassenlab/cellpose/assets/166049959/0ed1fc11-9f12-4a1e-9d5d-b8d23a01179e">

### Notes
A key shortcut can be added to this, but only if you enjoy doing that (not important at this point).
This is very similar to #30 , either the same developer does this or contact the developer that is assigned to #30 .
