### ISSUE TITLE
fill json with information for export

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#35]
**As a** Cellpose user, **I want** to fill the json with relevant information, **so that** I can export my settings.

**effort estimate:**
Team 1: 8
Team 2: 21

### Acceptance Criteria

For example if I:
1. Click on the "Save Settings as json" button
2. a json file is saved that contains relevant information (see below).

And: 

- [ ] The json is structured in a way that it can later be imported and settings can be applied (just use a normal json structure)
- [ ] The json contains all loaded channels in the same order as in cellpose or holds information about the order

- [ ] The json contains for each channel:

1.  Identifier (e.g. "channel1")
2. Colour
3. Currently applied saturation
4.  The state: ON/OFF

- [ ] The json file either holds an empty place for "group" or is extendable to do so

### Additional Resources:

This could look roughly like this:

<img width="527" alt="Bildschirmfoto 2024-06-11 um 17 09 54" src="https://github.com/claassenlab/cellpose/assets/166049959/03068c0a-1213-43c1-b081-be42e4cee839">
