### ISSUE TITLE
position and size information of the drawing area contents (minimap orientation)

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#40]
**As a** Developer, **I want** to get position and size informations of the drawing area contents and save them, **so that** I can later use them to scale and place the highlight area of the minimap.

### Acceptance Criteria

If the view of the image is changed in any way, information on position and view field should be updated and easily accessible for other Developers.

#### Requirements:
- [x] New method that triggers, whenever the image is moved or zoomed in/out on (drawing area size adjustents also change the view of the image); 

In this method save:
- [x] coordinates of the viewbox relative to the image (upper left corner is (x=0,y=0);
- [x] width and height values relative to the image (if the image fits exactly the viewbox, vales are equal); 

In the PR:

- [x] Give an explanation on what the saved values stand for (easy understanding of other devs).

### Additional Resources:

I did some research and fount a potential way to obtain those values:

The image is displayed via the [viewbox](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/viewbox.html) feature of pyqt. To get values on position and size you could use the `viewRect()` method on the viewbox in cellpose. 

Example:

![grafik](https://github.com/claassenlab/cellpose/assets/148364763/25c5bbfc-9008-4ba4-9515-984268bc1670)

will result in:

![grafik](https://github.com/claassenlab/cellpose/assets/148364763/d4710618-4f74-462f-8f82-e496f2e8c22a)

for this view of an 800x800 image:

![Screenshot_1](https://github.com/claassenlab/cellpose/assets/148364763/91fde655-bc0c-47c6-a588-2267e93f559d)

To get information when something in the viewbox changes there is a signal `sigRangeChanged` of the viewbox.
