### ISSUE TITLE
display highlight area on the minimap (minimap orientation)

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#41]
**As a** Developer, **I want** an adjustable highlight area on the minimap, **so that** I can point out certain parts of the minimap.

### Acceptance Criteria

Constraints:
- [x] There is a new layer drawn on top of the minimap, that allows other graphics to be displayed;
- [x] The area is highlighted via the graphic of a white rectangle outline;
- [x] The highlight area is adjustable in position and size;
- [x] The size of the area doesn't get bigger then the minimap (cap width & height).

### Additional Resources:

This is what the highlight area might look like:
<img width="993" alt="329233649-a6133e05-872e-466f-be8f-0f9d341ed983" src="https://github.com/claassenlab/cellpose/assets/148364763/3a9c3be9-978d-4dae-8117-7eee0875cfb3">
![grafik](https://github.com/claassenlab/cellpose/assets/148364763/ca1bed3c-f233-4b9d-834b-38f6d984c07c)

 (Ignore the rest of the buttons/features of this minimap)
