### ISSUE TITLE
curser position information on mouseclick (minimap navigation)

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#44]
**As a** Developer, **I want** to obtain the position values of the current cursor position in the minimap dialog, upon a mouseclick **so that** I can later use them to change the view to the new position on my image.

### Acceptance Criteria

Requirements:
- [x] Override the mousePressEvent method in minimap class;
- [x] save coordinates of the mouseclick event to variables;
- [x] "normalize" these values*.

Since the mainwindow viewbox and our minimap don't share a coordinate system, we need to somehow normalize the values*, so they can be applied to the mainwindow viewbox. (dividing by minimap width/length will probably do the trick).

### Additional Resources:

If the top left corner of the minimap gets clicked, the values should be:
`x=0, y=0; normalized: x=0, y=0`

and in the center:
`x=?,y=?; normalized: x=0.5, y=0.5`

### Notes

*Since we work with the viewbox now, we could use the method  mapToView, which gives you the position in the coordinate system of the viewbox, this then wouldn't require normalizing and might be more optimal.
