### ISSUE TITLE
move the view of the viewbox to a given position (minimap navigation)

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#45]
**As a** Developer, **I want** to point the center of view on the given position in the image, **so that** I can jump to other locations of the image with given coordinates.

### Acceptance Criteria
 
Requirements:
- [x] new method that takes normalized* x,y coordinates as an input;
- [x] upon calling the method, the center of the viewbox is pointed on the image according to the coordinates;
- [x] the method should only change the view on the image, not move the image around;
- [x] the part of the picture that is shown is the same size as the part that was shown before the change (same level of zoom).

### Additional Resources:
Given normalized coordinates `x=0.5, y=0.5` this should be the view:
![grafik](https://github.com/claassenlab/cellpose/assets/148364763/d26a8fab-2705-4ae3-aba2-743289d7cc35)
for normalized coordinates `x=1, y=1` 
![grafik](https://github.com/claassenlab/cellpose/assets/148364763/de1433e7-f877-46a6-ac72-54bfd8198c3d)
or with a different amount of zoom and changed window size:
![grafik](https://github.com/claassenlab/cellpose/assets/148364763/407a0056-fa8f-4a4f-9be0-d782fb7315b5)

### Notes

*Again, this might work better with the mapToView method, then we would work with coordinates fitting the image dimensions.

This method will be called via the `mousePressEvent` method implemented in #44.

There are multiple ways to change the view of the viewbox, i didn't find an optimal yet. Worth looking at is the method 
`<your viewbox>.translateBy(x=?,y=?)` since this will change the view by an amount, it would be necessary to check for the current position of the image and take it into account when moving the view.
