### ISSUE TITLE
navigate via the minimap (minimap navigation)

### ISSUE THREAD

**Issue by jakobjo** [claassenlab/cellpose#46]
**As a** User, **I want** to click on a position of the minimap and have my main window view box adjust itself accordingly, **so that** I can navigate in my image via the minimap.

### Acceptance Criteria

For example:
1. If I click somewhere with my cursor on the minimap, 
2. the point of the click becomes the new center of my view in the main window.

Requirements:
- [ ] take the obtained normalized coordinates of issue #44 and call the method implemented by issue #45 ;
- [ ] the center should be precisely where the user clicked on the minimap;
- [ ] the highlight area should be updated if the view of the image is changed.

### Notes

This combines #44 and #45 and completes the minimap feature.
