### ISSUE TITLE
channel sliders and buttons initialization

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#50]
**As a** User, **I want** as many colour dialog buttons, on/off buttons and sliders to appear as there are channels/layers loaded, **so that** I can later adjust the visualization using them.

### Acceptance Criteria

For example:
1. Import a tiff image with N layers
2. N Markers appear in the right side menu, each has: A colour dialog, a on/off button and a slider.

Or:
- [ ] The first three colour buttons are initially [red, green, blue], the rest have no colour
- [ ] The first three channels ON/OFF buttons are initially ON, the rest is OFF
- [ ] This should only be triggered when multi-layer 2D tiff images are loaded
- [ ] When e.g. a png is loaded, the normal cellpose layout is there (three sliders/channels)

### Additional Resources:

<img width="357" alt="Bildschirmfoto 2024-07-14 um 15 22 54" src="https://github.com/user-attachments/assets/697c7763-e3a1-4295-b2e8-23fccef0eed7">

The eyes for the first three channels should be open.
