### ISSUE TITLE
display multichannels

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#51]
Effort: 21

**As a** Cellpose user, **I want** the loaded channels to display in the main window, **so that** I can see them.

### Acceptance Criteria

For example:
1. I load a multi-layer 2D tiff image into cellpose
2. the composition of the layers is displayed in the main window.

- [ ] The layers are shown in the main window (on top of each other)
- [ ] This happens ONLY when a 2D multi-layer tiff image is loaded
- [ ] If no 2D multi-layer tiff image is loaded cellpose functions as before

### Notes

An environment variable could be helpful for differentiating the cases (multi-layer tiff vs anything else)

See my example implementation on discord, if inspiration is needed. But it can surely be done more efficient than I did.
