### ISSUE TITLE
on/off buttons for channels

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#52]
Effort: 8

**As a** Cellpose user, **I want** on/off buttons for each layer/channel of the tiff image I imported, **so that** I can only see the channels that I want.

### Acceptance Criteria

For example:
1. I load a tiff image with N layers
2. N on/off buttons appear on the right
3. the N-th layer/channel can be turned ON/visible or OFF/invisible with the N-th button

- [ ] The buttons that were already implemented are used
- [ ] This only happens if a multi layer 2D tiff image is loaded
- [ ] If anything else is loaded cellpose functions as before

### Notes

Use the buttons which are already implemented. Making a channel invisible can be achieved by setting its alpha channel to fully transparent.
If you're a pro you make sure that the channels which are turned off skipped in the calculation of composite picture. This can save many calculations.

See my example implementation on discord if needed.
