### ISSUE TITLE
custom color for channels

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#53]
Effort: 5

**As a** Cellpose user, **I want** that each layer of the tiff image I import can be colorized, **so that** I can differentiate the channels visually.

### Acceptance Criteria

If the user...
1. Loads an N-layered tiff image
2. N colour dialogs appear on the right
3. The N-th colour dialog button can set the N-th channels colour

- [x] Use the colour dialogs which are already implemented for this
- [x] This should only happen when a multi-layer 2D tiff image is imported
- [x] Cellpose functions as before if a different format is loaded (not multi layer tiff)

### Additional Resources:
The current colour dialogs, which were implemented for this.

<img width="884" alt="Bildschirmfoto 2024-07-14 um 21 05 57" src="https://github.com/user-attachments/assets/c5520b4d-e130-4163-858a-88c9ea7893b4">

### Notes

See my example implementation on discord if needed, there I colourized the channels by merging them with coloured images.

Initial state of colours will be set later, so it doesn't matter right now.
