### ISSUE TITLE
sliders for each channel

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#54]
Effort: 8

**As a** Cellpose user, **I want** a slider in the right hand side menu for each channel, **so that** I can adjust the channels' visibility.

### Acceptance Criteria

1. If I import a tiff image with N layers 
2. N sliders appear (next to the buttons corresponding to the channels)
3. The sliders control the upper and lower bounds (explaination below)

And:
- [ ] The N sliders only appear when a multi-layered 2D tiff image is imported
- [ ] The sliders are the same which are already implemented
- [ ] If anything else is imported (no multi-layered tiff image) Cellpose works as before
- [ ] The right hand side part of each slider controls the upper- and the left hand side of each slider the lower bound of the corresponding channel/layer.
- [ ] The right and left parts of the sliders cannot pass by each other (as implemented now, this means that the upper_bound >= lower bound is ensured)
- [ ] Division-by-zero cases are properly handled/avoided, so no errors occur (these can occur when lower bound = upper bound)

### Additional Resources:

The upper and lower bound sliders are designed to control the contrast of the image by adjusting the pixel values to fall within a specified range. 

More specifically this means:
(1) Each pixel value is reduced by the lower bound. This shifts the pixel values so that the lower bound becomes the new zero point.
(2) After shifting, the pixel values are divided by the range (upper bound - lower bound). This normalizes the pixel values to a 0 to 1 range.
(3) The normalized pixel values are then scaled to the full [0, 255] range,

See the documentation for this operation:
https://numpy.org/doc/stable/reference/generated/numpy.clip.html

These are the sliders (as implemented right now):

<img width="364" alt="Bildschirmfoto 2024-07-14 um 21 54 52" src="https://github.com/user-attachments/assets/38a4f971-b63f-4822-86f8-f446721184f1">

### Notes

See my implementation on discord if you need help, or ask me directly.
