### ISSUE TITLE
multi-channel initialization

### ISSUE THREAD

**Issue by Davidundso** [claassenlab/cellpose#55]
Effort: 13

**As a** Cellpose user, **I want** the colours, sliders and on/off buttons to initialize correctly, **so that** I have a good initial setting for analyzing multichannel tiff images.

### Acceptance Criteria

If the loaded multi-layer tiff image has N layers:

- [x] N on_off buttons appear (those that are already implemented, in ON state)
- [x] N colour dialog buttons appear (those which are already implemented, see initial colours below)
- [x] N sliders appear (those which are already implemented)
- [x] N marker-names appear: Starting with "Marker 1", "Marker 2", ..., "Marker N"
- [x] The on_off buttons do not appear anymore in the normal cellpose (when no multi layer image is loaded)
- [x] The colour buttons do not appear anymore in the normal cellpose (when no multi layer image is loaded)
- [x] The marker names do not appear anymore in the normal cellpose (when no multi layer image is loaded)

Optional:
- [x] The red, green, blue names are back as in cellpose before multi channel support when no multi layered tiff is loaded (see screenshot below)

### Additional Resources:

These are the inital values:
colors = [
    (255, 0, 0),    # Red
    (0, 255, 0),    # Green
    (0, 0, 255),    # Blue
    (255, 255, 0),  # Yellow
    (255, 0, 255),  # Magenta
    (0, 255, 255),  # Cyan
    (255, 165, 0)   # Orange
]

The sliders in case of no multi layered tiff:

<img width="231" alt="Bildschirmfoto 2024-08-08 um 17 47 24" src="https://github.com/user-attachments/assets/46f8dcc9-b20d-4307-b712-054922e61558">

This is how the first three channel menus could look like in case of a multi layered tiff:

<img width="355" alt="Bildschirmfoto 2024-07-15 um 10 48 00" src="https://github.com/user-attachments/assets/8716903b-64a7-4698-afa3-ac8553dc178d">
